from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setMouseTracking(False)
        self.frame.setStyleSheet("background-color: #fce9a9")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(165, 190, 771, 101))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(100)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(300, 200, 55, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(310, 40, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:#fff000; border-radius: 10px")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(380, 40, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:#fff000; border-radius: 10px")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(450, 40, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:#fff000; border-radius: 10px")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(520, 40, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:#fff000; border-radius: 10px")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(240, 40, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(22)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:#fff000; border-radius: 10px")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.Play = QtWidgets.QPushButton(self.frame)
        self.Play.setEnabled(False)
        self.Play.setGeometry(QtCore.QRect(215, 400, 421, 81))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Play.setFont(font)
        self.Play.setStyleSheet("background-color: #b3b300; border-radius: 10px ;")
        self.Play.setObjectName("Play")
        self.word = QtWidgets.QLineEdit(self.frame)
        self.word.setGeometry(QtCore.QRect(180, 300, 480, 60))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.word.setFont(font)
        self.word.setStyleSheet("background-color:#fff")
        self.word.setObjectName("word")
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setKerning(True)
        self.mistake = QtWidgets.QLabel(self.frame)
        self.mistake.setGeometry(QtCore.QRect(90, 140, 600, 55))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(25)
        self.mistake.setFont(font)
        self.mistake.setText("")
        self.mistake.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mistake.setObjectName("mistake")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "5 Букв"))
        self.label.setText(_translate("MainWindow", "Загадайте 5-ти буквенное слово"))
        self.label_5.setText(_translate("MainWindow", "Б"))
        self.label_6.setText(_translate("MainWindow", "У"))
        self.label_8.setText(_translate("MainWindow", "К"))
        self.label_9.setText(_translate("MainWindow", "В"))
        self.label_10.setText(_translate("MainWindow", "5"))
        self.Play.setText(_translate("MainWindow", "загадать"))
